### PR TITLE
Append script on body tag instead of head

### PR DESCRIPTION
**Pull request by samwx**

### CODE REVIEW

**Comment by samwx** [comment]
@mmathias01 :(

**Comment by mmathias01** [comment]
I am sorry that took so long. Merged.

It could make sense depending on the individual use case to just allow someone to pass in an element as the append target but default to body.

**Comment by samwx** [comment]
Thank you!

I'll make one more PR. Packages can be dynamic, passed by user, because Google Charts have a lot of chart options that won't be applied on "corecharts", like tables, imagesparkline and others.

May I?

**Comment by mmathias01** [comment]
This is already supported. See the README. You can pass the additional types in as part of the load function and once the script is loaded it will also load the additional packages.

**Comment by samwx** [comment]
@mmathias01 Sorry, I see that we can do this now, passing packages as second parameter on load method. Thank you anyway :)

**Comment by mmathias01** [comment]
@samwx no worries! glad you are getting some usage out of it!

**Pull request merged**
